### ISSUE TITLE
Lookup/Port page - Trim duplicate fields and headers

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#222]
**How will this improve revenue or reduce our costs? Please provide a complete explanation!**
Removing duplicate and useless data and headers will enable our customers and team to move through the porting process with less confusion and make fewer errors

**Is your feature request related to a problem? Please describe.**
Currently the porting page shows each phone number in 3 separate places, and the city and state of the number is always unknown as you can see below ([from this link](https://acceleratenetworks.com/Lookup/BulkPort?dialedNumber=2068589310%0D%0A4254997999%0D%0A2068588757%0D%0A2065579451))

![image](https://user-images.githubusercontent.com/1683673/130313883-03930483-de73-4c86-a525-62a9f1e4ee05.png)

**Describe the solution you'd like**
Trim this page down to something like this mockup:

![image](https://user-images.githubusercontent.com/1683673/130314167-d10e1e4c-13aa-4600-855f-b83a0afc0287.png)

**Comment by uncheckederror** [comment]
@danry25 Should we add buttons to jump to the wireless and non-wireless number sections, if they exist?

**Comment by TakoyakiAllenC** [comment]
Hi. I'm a customer and I'd like leaner rows. I found it hard to read with so much bulk. I had to zoom out to 50% scale to even get through clicking 30+ add to carts over and over.

**Comment by uncheckederror** [comment]
@TakoyakiAllenC I have leaned out the rows. How does this look to you?

![localhost_44316_Lookup_BulkPort_dialedNumber=%28206%29%2B329-0786%0D%0A%28206%29%2B329-9442%0D%0A%28206%29%2B717-0076%0D%0A%28206%29%2B717-0077%0D%0A%28206%29%2B717-0078%0D%0A%28206%29%2B717-0079%0D%0A%28206%29%2B7](https://user-images.githubusercontent.com/11726956/130333772-f98b5f43-1a9e-42c2-bb7f-0b8950a0957a.png)

**Comment by TakoyakiAllenC** [comment]
If I could marry websites legally, I'd propose.

**Comment by danry25** [comment]
@uncheckederror I see that the T-Mobile numbers are still mixed into the main list in your screenshot? Additionally, since the Transfer and Investigate buttons do nearly the same thing and provide similar data, could we consolidate these into just a green Search button?

@TakoyakiAllenC Hahaha, your comment makes me think of Futurama's Proposition Infinity episode, where the plot line is a ballot initiative similar to California's Prop 8, but instead for robots and humans.

**Comment by TakoyakiAllenC** [comment]
> 
> 
> @TakoyakiAllenC I have leaned out the rows. How does this look to you?
> 
> ![localhost_44316_Lookup_BulkPort_dialedNumber=%28206%29%2B329-0786%0D%0A%28206%29%2B329-9442%0D%0A%28206%29%2B717-0076%0D%0A%28206%29%2B717-0077%0D%0A%28206%29%2B717-0078%0D%0A%28206%29%2B717-0079%0D%0A%28206%29%2B7](https://user-images.githubusercontent.com/11726956/130333772-f98b5f43-1a9e-42c2-bb7f-0b8950a0957a.png)

In your screenshot, you show tmobile numbers in the section for landlines. Did you change the functionality? New bug?

**Comment by uncheckederror** [comment]
I have fixed the bug where wireless numbers were shown in the local numbers section in 5269ca9.

**Comment by uncheckederror** [comment]
@danry25 @TakoyakiAllenC I have fixed up the duplication of the wireless numbers and combined the Investigate and Transfer buttons.

![image](https://user-images.githubusercontent.com/11726956/130345969-35c4adf9-86b9-4441-908e-a41daf562204.png)

**Comment by TakoyakiAllenC** [comment]
https://acceleratenetworks.com/Search still shows 2 buttons

![image](https://user-images.githubusercontent.com/79335475/130375444-4a65ebc8-65ad-4c6c-8e9b-331180e9bf91.png)

**Comment by danry25** [comment]
@TakoyakiAllenC this issue is about https://acceleratenetworks.com/Lookup not https://acceleratenetworks.com/Search

**Comment by achen4** [comment]
@danry25 - I'm just telling you that the same reason you should combine the buttons exist for /Search. Does not make sense to have a search button and a transfer button when you can just search and add items to cart. For your own tracking you may wish to split the issue into another issue but this was the most relevant issue to post on since the design should be uniform in my opinion.

**Comment by TakoyakiAllenC** [comment]
@danry25 - I'm just telling you that the same reason you should combine the buttons exist for /Search. Does not make sense to have a search button and a transfer button when you can just search and add items to cart. For your own tracking you may wish to split the issue into another issue but this was the most relevant issue to post on since the design should be uniform in my opinion.

**Comment by danry25** [comment]
@TakoyakiAllenC Well, @uncheckederror informed me that he preferred the single button solution that he originally implemented for https://acceleratenetworks.com/Search so I think we will revert to that.

I created issue #223 for this, @TakoyakiAllenC is there anything in the fields or headers on the /Lookup page that you would like adjusted?

**Comment by TakoyakiAllenC** [comment]
No. I think it's just fine now.
