### ISSUE TITLE
Initial spelled incorrectly

### ISSUE THREAD

**Issue by sewcialite** [AccelerateNetworks/NumberSearch#333]
**Describe the bug**
On the support pages, initial is spelled wrong. 

**To Reproduce**
1. Go to https://acceleratenetworks.com/Support
2. Click on any phone
3. 
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/8e34918a-f916-4705-8b4a-9a6addcebd47)
4. See it spelled srong

**Expected behavior**
Initial to be spelled correctly

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/87674023/cfbec146-21f2-4eed-8a47-e6a9e272b6e7)

**Comment by uncheckederror** [comment]
As far as I can tell initial was misspelled as "inititial" in one in the table of contents on the support pages for the GRP2615, GRP2135, and GRP2170. This should be resolved now, @sewcialite please verify.

**Comment by sewcialite** [comment]
It is still incorrect here, https://acceleratenetworks.com/Phones/T54W ,
but otherwise, appreciate the quick change.

**Comment by sewcialite** [comment]
It is still incorrect here, https://acceleratenetworks.com/Phones/T54W

**Comment by uncheckederror** [comment]
@sewcialite I believe this is fixed now. Apologies for the premature auto close.
