### ISSUE TITLE
Impossible tax rates

### ISSUE THREAD

**Issue by danry25** [AccelerateNetworks/NumberSearch#351]
**Describe the bug**
We are generating negative tax rates for out of state orders.

**To Reproduce**
1. Go to https://ops.acceleratenetworks.com/Home/Order/6997e874-dff2-4857-99bf-937b2b58a4cc

**Expected behavior**
No tax rate should have been applied to this order, especially not a Washington State tax rate given the client was outside Washington State.

**Screenshots**
![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/bdfd56ef-a9a6-4922-aa81-501d08d9d004)

**Additional context**
Generating any type of tax rate that is below 0% or above 13% should be a 5 alarm fire. Something has gone horribly wrong and we need to correct the invoice immediately.

**Comment by uncheckederror** [comment]
I have added additional validation to but the invoice generate in the checkout process and the invoice regeneration process in the Ops app that should resolve this issue. Please try it out.

**Comment by danry25** [comment]
@uncheckederror The bug is not fixed for the main invoice, only the recurring invoice is corrected. We now have three invoices where we give away thousands of dollars in free hardware, and one recurring invoice where we give away service.

Additionally, a modal of " Generated the invoices for this order! 🥳 Failed to find existing onetime and reoccurring invoices in the billing system 😡 " is shown every time you regenerate an invoice despite the prior invoice's information being saved:

![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/a218e7ae-229e-43d9-9bc9-15c255a59a25)


![image](https://github.com/AccelerateNetworks/NumberSearch/assets/1683673/74050fd7-196f-430e-ae01-0a104bc908b3)

**Comment by uncheckederror** [comment]
@danry25 try regenerating the invoices for this now. https://ops.acceleratenetworks.com/Home/Order/6997e874-dff2-4857-99bf-937b2b58a4cc/

**Comment by danry25** [comment]
Works now :D
